apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: ubuntu:18.04
          command:
            - "lynxi-smi"
          args:
            - "watch"
          resources:
            limits:
              lynxi.com/device: "2"
        - name: example2
          image: ubuntu:18.04
          command:
            - "lynxi-smi"
          args:
            - "watch"
          resources:
            limits:
              lynxi.com/device: "2"
