apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apu-feature-discovery
  namespace: {{ .Values.namespace.name }}
  labels:
    lynxi.com: apu-feature-discovery
spec:
  selector:
    matchLabels:
      lynxi.com: apu-feature-discovery
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        lynxi.com: apu-feature-discovery
    spec:
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      serviceAccountName: apu-feature-discovery-service-account
      containers:
        - image: {{ .Values.apuFeatureDiscovery.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: apu-feature-discovery
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apu-feature-discovery-cluster-role
  labels:
    lynxi.com: apu-feature-discovery-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apu-feature-discovery-cluster-role-binding
  labels:
    lynxi.com: apu-feature-discovery-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apu-feature-discovery-cluster-role
subjects:
- kind: ServiceAccount
  name: apu-feature-discovery-service-account
  namespace: {{ .Values.namespace.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apu-feature-discovery-service-account
  namespace: {{ .Values.namespace.name }}
  labels:
    lynxi.com: apu-feature-discovery-service-account
