kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: lynxi-daemon-set
  namespace: {{.Values.namespace.name}}
  labels:
    lynxi.com: lynxi-daemon-set
spec:
  selector:
    matchLabels:
      lynxi.com: lynxi-daemon-set
  template:
    metadata:
      labels:
        lynxi.com: lynxi-daemon-set
    spec:
      serviceAccountName: lynxi-device-discovery-service-account
      initContainers:
        - name: check-environment
          image: ubuntu:20.04
          command: ["/bin/sh"]
          args: ["-c", "if command -v lynxi-smi >/dev/null 2>&1; then echo 'exists lynxi-smi'; else echo 'no exists lynxi-smi, sleep infinity'; sleep infinity; fi"]
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: none
      containers:
        - name: lynsmi-service
          image: {{.Values.lynsmiService.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
        - name: lynxi-device-discovery
          image: {{.Values.lynxiDeviceDiscovery.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
        - name: lynxi-device-plugin
          image: {{.Values.lynxiDevicePlugin.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins/
            - name: localtime
              mountPath: /etc/localtime
{{if .Values.lynxiExporter.enable}}
        - name: lynxi-exporter
          image: {{.Values.lynxiExporter.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
          volumeMounts:
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources/
            - name: localtime
              mountPath: /etc/localtime
{{end}}
      volumes:
{{if .Values.lynxiExporter.enable}}
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources/
{{end}}
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: localtime
          hostPath:
            path: /etc/localtime
      nodeSelector: 
        lynxi.com/apu.present: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lynxi-device-discovery-cluster-role
  labels:
    lynxi.com: lynxi-device-discovery-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lynxi-device-discovery-cluster-role-binding
  labels:
    lynxi.com: lynxi-device-discovery-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lynxi-device-discovery-cluster-role
subjects:
  - kind: ServiceAccount
    name: lynxi-device-discovery-service-account
    namespace: {{.Values.namespace.name}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lynxi-device-discovery-service-account
  namespace: {{.Values.namespace.name}}
  labels:
    lynxi.com: lynxi-device-discovery-service-account
