kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: lynxi-daemon-set
  namespace: {{.Values.namespace.name}}
  labels:
    lynxi.com: lynxi-daemon-set
spec:
  selector:
    matchLabels:
      lynxi.com: lynxi-daemon-set
  template:
    metadata:
      labels:
        lynxi.com: lynxi-daemon-set
    spec:
      initContainers:
        - name: check-environment
          image: ubuntu:18.04
          command: ["/bin/sh"]
          args: ["-c", "if command -v lynxi-smi >/dev/null 2>&1; then echo 'exists lynxi-smi'; else echo 'no exists lynxi-smi, sleep infinity'; sleep infinity; fi"]
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: none
      containers:
        - name: lynsmi-service
          image: lynxidocker/lynsmi-service:1.5.0
          imagePullPolicy: {{.Values.imagePullPolicy}}
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
        - name: lynxi-device-plugin
          image: {{.Values.lynxiDevicePlugin.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins/
            - name: localtime
              mountPath: /etc/localtime
{{if .Values.lynxiExporter.enable}}
        - name: lynxi-exporter
          image: {{.Values.lynxiExporter.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
          volumeMounts:
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources/
            - name: localtime
              mountPath: /etc/localtime
{{end}}
      volumes:
{{if .Values.lynxiExporter.enable}}
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources/
{{end}}
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: localtime
          hostPath:
            path: /etc/localtime
      nodeSelector: 
        lynxi.com/apu.present: "true"