{{if .Values.devicePluginHS110Kubeedge.enable}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{.Values.devicePluginHS110Kubeedge.name}}
  namespace: {{.Values.devicePluginHS110Kubeedge.namespace}}
  labels: 
{{toYaml .Values.devicePluginHS110Kubeedge.labels | indent 4}}
spec:
  selector:
    matchLabels:
{{toYaml .Values.devicePluginHS110Kubeedge.labels | indent 6}}
  template:
    metadata:
      labels:
{{toYaml .Values.devicePluginHS110Kubeedge.labels | indent 8}}
    spec:
      containers:
        - name: {{.Values.devicePluginHS110Kubeedge.name}}
          image: {{.Values.devicePluginHS110Kubeedge.image}}
          imagePullPolicy: {{.Values.devicePluginHS110Kubeedge.imagePullPolicy}}
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/edged/device-plugins
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/edged/device-plugins
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: {{.Values.devicePluginHS110Kubeedge.restartPolicy}}
      nodeSelector: 
{{toYaml .Values.devicePluginHS110Kubeedge.nodeSelector | indent 8}}
      tolerations: 
{{toYaml .Values.devicePluginHS110Kubeedge.tolerations | indent 8}}
{{end}}