{{if .Values.lynxiExporter.enable}}
kind: Service
apiVersion: v1
metadata:
  name: lynxi-exporter-service
  namespace: {{.Values.namespace.name}}
  labels: 
    lynxi.com: lynxi-exporter-service
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
  selector: 
    lynxi.com: lynxi-daemon-set
{{end}}