{{if .Values.lynxiExporter.enable}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{.Values.lynxiExporter.name}}
  namespace: {{.Values.lynxiExporter.namespace}}
  labels:
{{toYaml .Values.lynxiExporter.labels | indent 4}}
spec:
  selector:
    matchLabels:
{{toYaml .Values.lynxiExporter.labels | indent 6}}
  template:
    metadata:
      labels:
{{toYaml .Values.lynxiExporter.labels | indent 8}}
    spec:
      initContainers:
        - name: check-environment
          image: ubuntu:18.04
          command: ["/bin/sh"]
          args: ["-c", "if command -v lynxi-smi >/dev/null 2>&1; then echo 'exists lynxi-smi'; else echo 'no exists lynxi-smi, sleep infinity'; sleep infinity; fi"]
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: none
      containers:
        - name: {{.Values.lynxiExporter.name}}
          image: {{.Values.lynxiExporter.image}}
          imagePullPolicy: {{.Values.lynxiExporter.imagePullPolicy}}
          ports:
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/pod-resources/
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/pod-resources/
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: {{.Values.lynxiExporter.restartPolicy}}
      nodeSelector: 
{{toYaml .Values.lynxiExporter.nodeSelector | indent 8}}
      tolerations: 
{{toYaml .Values.lynxiExporter.tolerations | indent 8}}
{{end}}