{{if .Values.lynxiExporter.enable}}
{{if .Values.lynxiExporter.serviceMonitor.enable}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lynxi-exporter-service-monitor
  namespace: {{.Values.namespace.name}}
  labels:
    lynxi.com: lynxi-exporter-service-monitor
spec:
  selector:
    matchLabels:
      lynxi.com: lynxi-exporter-service
  namespaceSelector:
    matchNames:
      - {{.Values.namespace.name}}
  endpoints:
    - interval: {{.Values.lynxiExporter.serviceMonitor.interval}}
      path: /metrics
      port: http-metrics
      scheme: http
{{end}}
{{end}}