apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apu-feature-discovery
  labels:
    app.kubernetes.io/name: apu-feature-discovery
    app.kubernetes.io/version: 0.1.1
    app.kubernetes.io/part-of: lynxi-apu
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apu-feature-discovery
      app.kubernetes.io/part-of: lynxi-apu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apu-feature-discovery
        app.kubernetes.io/version: 0.1.1
        app.kubernetes.io/part-of: lynxi-apu
    spec:
      containers:
        - image: lynxidocker/apu-feature-discovery:0.1.1
          name: apu-feature-discovery
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName