kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: lynxi-device-plugin
  labels:
    lynxi.com: lynxi-device-plugin
spec:
  selector:
    matchLabels:
      lynxi.com: lynxi-device-plugin
  template:
    metadata:
      labels:
        lynxi.com: lynxi-device-plugin
    spec:
      containers:
        - name: lynxi-device-plugin
          image: "lynxidocker/lynxi-device-plugin-hs110-k8s:1.2.0"
          imagePullPolicy: Always
          env:
            - name: LYNXI_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
      restartPolicy: Always
