sleepInterval: 60s

nameOverride: ""
fullnameOverride: ""

namespace:
  # Name of the namespace to put all components in
  name: lynxi
  # Specifies whether this namespace should be created or not
  create: true

imagePullSecrets: []
image:
  repository: lynxidocker/apu-feature-discovery
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podSecurityContext: {}
securityContext:
  privileged: true

resources: {}
affinity: {}
tolerations: {}

serviceAccount:
  # Name of the service account to use (whether existing or to be created)
  # [Default: $fullname-master if set to empty string]
  name: ""
  # Specifies whether this service account should be created or not
  create: true
  # Annotations to add to the service account when creating it
  annotations: {}

rbac:
  # Role to associate with the service account above (whether existing to to be created)
  # [Default: $fullname-master if set to empty string]
  role: ""
  # Specifies whether this role should be created or not
  create: true

