namespace:
  name: project-lynxi
  create: true

imagePullPolicy: Always

lynxiDevicePlugin:
  image: lynxidocker/lynxi-device-plugin:1.5.0

lynxiExporter:
  enable: true
  image: lynxidocker/lynxi-exporter:1.5.0
  serviceMonitor:
    enable: true
    interval: 0.5s

apuFeatureDiscovery:
  image: lynxidocker/apu-feature-discovery:1.5.0
