apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lynxi-exporter-service-monitor
  namespace: project-system
  labels:
    name: lynxi-exporter-service-monitor
spec:
  selector:
    matchLabels:
      lynxi.com: lynxi-exporter
  namespaceSelector:
    matchNames:
      - project-system
  endpoints:
    - interval: 5s
      path: /metrics
      port: http-metrics
      scheme: http
